service: webscrapper-serverless



frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1

functions:
  webscrapper:
    handler: webscrapper.handle
    memorySize: 1024
    timeout: 300
    events:
      - http:
          path: /test
          method: get
          cors: true
          private: false
